name: "Tanner Linting Report"
description: "This lints the changed files within a Pull Request and adds comments onto the PR for the developer to correct."
author: "Tanner Smith"

runs:
    using: "composite"
    steps:
      # - uses: actions/checkout@v3
      # - name: Setup Node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16
      #     cache: 'npm'
      # - name: Install Node Dependencies
      #   run: npm ci
      #   env:
      #     CI: TRUE
      # - name: Get Changed Files
      #   id: changed-files
      #   uses: tj-actions/changed-files@v39.2.3
      #   with:
      #     separator: ","
      #     files_ignore_separator: ","

      # - name: Install Eslint
      #   run: npm install eslint --global

      - name: Save Code Linting Report JSON
        shell: bash
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo $file
          eslint . --ext .js --output-file eslint_report.json --format json src
          # Continue to the next step even if this fails
          done
        
        continue-on-error: true

      # - name: Annotate Code Linting Results
      #   uses: ataylorme/eslint-annotate-action@v2
      #   with:
      #     report-json: "eslint_report.json"
